require "bundler/setup"
begin
  require 'jeweler/tasks'
  Jeweler::Tasks.install_tasks
rescue LoadError
  Bundler::GemHelper.install_tasks
end

<% rakefile_head_snippet_plugins.each do |plugin| %>
<%= plugin.rakefile_head_snippet %>
<% end %>

<% rakefile_snippet_plugins.each do |plugin| %>
<% plugin.rakefile_snippets.each do |snippet| %>
<%= snippet %>
<% end %>
<% end %>

task :default => :<%= testing_framework_base.default_rake_task %>
